Update NuGet-Checker.yml

diff --git a/.github/workflows/NuGet-Checker.yml b/.github/workflows/NuGet-Checker.yml
--- a/.github/workflows/NuGet-Checker.yml
+++ b/.github/workflows/NuGet-Checker.yml
@@ -21,11 +21,11 @@ jobs:
         working-directory: main
         run: |
           if [ "$(git ls-remote --heads origin update-nuget)" != "" ]; then
-            echo "::error ::Branch update-nuget exist. Merge PR or delete the branch" && exit 1
+            echo "::error ::Branch update-nuget exist. Merge PR or delete the branch"
+            exit 1
           fi
 
       - name: Flatpak Cache
-        if: false
         uses: actions/cache@v3
         with:
           path: |
@@ -35,7 +35,6 @@ jobs:
             flatpak
 
       - name: Setup Dependencies
-        if: false
         run: |
           sudo apt update -y
           sudo apt install flatpak -y
@@ -44,14 +43,12 @@ jobs:
           sudo su $(whoami) -c 'flatpak install flathub org.flatpak.Builder -y'
 
       - name: Set ENV Variables
-        if: false
         run: |
           echo "RUNTIME-VERSIONFROMYAML=$(yq '.runtime-version' main/org.jellyfin.JellyfinServer.yml)" >> "$GITHUB_ENV"
           echo "DOTNETSDKFROMYAML=$(yq '.sdk-extensions[0]' main/org.jellyfin.JellyfinServer.yml)" >> "$GITHUB_ENV"
           echo "TAGFROMYAML=$(yq '.modules[-1].sources[2].tag' main/org.jellyfin.JellyfinServer.yml)" >> "$GITHUB_ENV"
 
       - name: Checkout Jellyfin
-        if: false
         uses: actions/checkout@v3
         with:
           repository: jellyfin/jellyfin
@@ -59,14 +56,12 @@ jobs:
           ref: ${{ env.TAGFROMYAML }}
 
       - name: Checkout Flatpak Builder Tools
-        if: false
         uses: actions/checkout@v3
         with:
           repository: flatpak/flatpak-builder-tools
           path: flatpak-builder-tools
 
       - name: Generate cache for NuGet
-        if: false
         run: |
           sudo su $(whoami) -c 'flatpak install flathub ${{ env.DOTNETSDKFROMYAML }}//${{ env.RUNTIME-VERSIONFROMYAML }} -y'
           ./flatpak-builder-tools/dotnet/flatpak-dotnet-generator.py \
@@ -75,11 +70,9 @@ jobs:
             --runtime=linux-arm64 main/nuget-generated-sources-arm64.json jellyfin/Jellyfin.Server/Jellyfin.Server.csproj
 
       - name: Create Pull Request
-        if: false
         uses: peter-evans/create-pull-request@v5
         with:
           path: main
-          # branch-suffix: random
           title: Update NuGet Cache
           commit-message: Update NuGet Cache
           branch: update-nuget
